services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity   # Keep container running
    volumes:
      - ../../backend/src:/workspace/src
      - ../../backend/Cargo.toml:/workspace/Cargo.toml
      - ../../backend/Cargo.lock:/workspace/Cargo.lock
    ports:
      - "8000:3000"
    env_file:
      - ../.env
    tty: true
    stdin_open: true
    networks:
      - backend-network

  db:
    image: mariadb:12.2-noble
    restart: unless-stopped
    env_file: ../.env
    networks:
      - backend-network
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -uroot -p$$MARIADB_ROOT_PASSWORD"]
      interval: 10s
      retries: 5
    stdin_open: true 
    tty: true
  minio:
    image: minio/minio
    env_file:
      - ../.env
    command: server /data --console-address ":9001"
    restart: unless-stopped
    networks:
      - backend-network
    ports:
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio:9000/minio/health/live"]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 3s

networks:
  backend-network:
    driver: bridge