// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ID } from "./ID";

export type StandardUserView = { id: ID, name: string, email: string, is_admin: boolean, created_at: string, modified_at: string, };
